name: CI/CD - HSQ CRM Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------------
      # Configure AWS Credentials
      # ----------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 533284743348.dkr.ecr.ap-south-1.amazonaws.com

      # ----------------------------
      # Build Docker Image (with build arg)
      # ----------------------------
      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL=https://www.hsqtower.org\
            -t hsq-crm-client .

      - name: Tag Docker image
        run: |
          docker tag hsq-crm-client:latest \
          533284743348.dkr.ecr.ap-south-1.amazonaws.com/hsq-crm-client:latest

      - name: Push Docker image to ECR
        run: |
          docker push 533284743348.dkr.ecr.ap-south-1.amazonaws.com/hsq-crm-client:latest

      # ----------------------------
      # Deploy on Remote EC2
      # ----------------------------
      - name: Deploy Frontend on Remote Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ubuntu
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Logging into ECR..."
            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin 533284743348.dkr.ecr.ap-south-1.amazonaws.com

            echo "Stopping old frontend container..."
            docker stop hsq_crm_client || true
            docker rm hsq_crm_client || true

            echo "Pulling latest frontend image..."
            docker pull 533284743348.dkr.ecr.ap-south-1.amazonaws.com/hsq-crm-client:latest

            echo "Running new frontend container..."
            docker run -d -p 8080:80 \
              --name hsq_crm_client \
              533284743348.dkr.ecr.ap-south-1.amazonaws.com/hsq-crm-client:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
